### PR TITLE
Fixed mouse wheel in html5 target

### PR DESCRIPTION
**Pull request by jefvel**

### CODE REVIEW

**Comment by memilian** [comment]
This removed the wheel support for firefox. FF does not have any mousewheel event, just a wheel event

**Comment by RobDangerous** [comment]
Looks like we're running in circles but that kind of fits the topic.

**Comment by jefvel** [comment]
hehe, yeah. Assigning both onwheel and onmousewheel seemed to fix it. However the deltaY values differ in different browsers.

**Comment by jefvel** [comment]
#293 there's a pull request. is it possible to reopen pull requests?

**Comment by RobDangerous** [comment]
Maybe. If not you can just create a new one from the same branch.

**Pull request merged**
