### PR TITLE
Instanced schedulers for multi-window-projects

### PR DESCRIPTION
**Pull request by psmtec-dklein**
Hi Robert,

this PR adds multiple schedulers in addition to the singleton kha.Scheduler. Updating multi-window projects didn't properly work with the singleton one only. I experienced a lot of stuttering frames (looked like limited framerate to '60 / window_count' fps; the new version runs the Scheduler.executeFrame for each window. I also tried to dabble around with vsync ((un)forcing it via driver; implement glXSwapInterval etc), before this change, but it didn't really work out. With the new schedulers, everything is smooth now. 

1) i added kha.internal.InstancedScheduler (basically just a copy'n'paste version of kha.Scheduler with class member instead of statics
2) kha.Scheduler now has a 'static var global : InstancedScheduler' member and i inlined all existing functions to forward to this global instance (so everything should work as before and other projects aren't affected)
3) kha.Scheduler has an array of InstancedScheduler (and addInstance(), getInstance(id: Int)) for multi-window projects.

### CODE REVIEW

**Comment by psmtec-dklein** [comment]
found one issue, will reopen when fixed

**Comment by RobDangerous** [comment]
Can you provide a small test project, demonstrating the stuttering? Would like to have a closer look, make sure we properly solve the actual problem.

**Comment by sh-dave** [comment]
Sure, will do tomorrow when i'm back at work.

**Comment by psmtec-dklein** [comment]
Have a repo up now: https://github.com/psmtec-dklein/kha-issue-344
It requires the https://github.com/psmtec-dklein/Kha/tree/multi-scheduler to compile

**Comment by RobDangerous** [comment]
Thanks! Will analyze it tomorrow, when I'm back from work.

**Comment by sh-dave** [comment]
Hm, i investigated a bit more (had strange things happening in a singlewindow build as well) and i think it's the time-tasks that are not working properly (or i'm using something wrong). As soon as i add more than 1 ```Scheduler.addTimeTask(...)``` the movement becomes choppy. Simple test code (without Delta-lib dependency):

```haxe
package;

class State {
	public var rx = 32.0;
	public var lt : Float;
	public var speed = 400.0;

	public function new() {}
}

class Main {
	static var a = new State();
	static var b = new State();
	static var c = new State();

	public static function main() {
		kha.System.init( { title : 'MoreSchedulerStrangeness', width : 800, height : 600 }, setup);
	}

	static function setup() {
		kha.System.notifyOnRender(render);

// choppy as soon as more than 1 time-task is added
		kha.Scheduler.addTimeTask(updateState.bind(a), 0, 1 / 60);
		kha.Scheduler.addTimeTask(function() { }, 0, 1 / 60);

		//kha.Scheduler.addTimeTask(updateState.bind(a), 0, 1 / 60);
		//kha.Scheduler.addTimeTask(updateState.bind(b), 0, 1 / 60);
		//kha.Scheduler.addTimeTask(updateState.bind(c), 0, 1 / 60);

// ok
		//kha.Scheduler.addFrameTask(updateState.bind(a), 0);
		//kha.Scheduler.addFrameTask(updateState.bind(b), 1);
		//kha.Scheduler.addFrameTask(updateState.bind(c), 2);

// ok
		//kha.Scheduler.addFrameTask(function() {
			//updateState(a);
			//updateState(b);
			//updateState(c);
		//}, 0);

// ok
		//kha.Scheduler.addTimeTask(function() {
			//updateState(a);
			//updateState(b);
			//updateState(c);
		//}, 0, 1 / 60);

		a.lt = b.lt = c.lt = kha.Scheduler.time();
	}

	static function updateState( s : State ) {
		var now = kha.Scheduler.time();
		var dt = now - s.lt;
		s.lt = now;
		var d = s.speed * dt;
		s.rx += d;

		if (s.rx < 32 || s.rx > kha.System.windowWidth() - 128) {
			s.speed *= -1;
			s.rx -= d;
		}
	}

	static function render( fb : kha.Framebuffer ) {
		var g2 = fb.g2;

		g2.begin();
			g2.fillRect(a.rx, 16, 64, 64);
			g2.fillRect(b.rx, 128, 64, 64);
			g2.fillRect(c.rx, 240, 64, 64);
		g2.end();
	}
}

```

**Comment by RobDangerous** [comment]
Oho, I can see it. Fix in progress...

**Comment by RobDangerous** [comment]
That was a super important fix, good thing you can spot 60Hz vs 30Hz differences. Can you check if it also fixes your multi-window-problems?

**Comment by sh-dave** [comment]
Will to first thing monday morning.

**Comment by psmtec-dklein** [comment]
Working just fine now :+1:

**Comment by ImmanuelSamuel** [comment]
@psmtec-dklein could you reupload the multi window test project? or maybe someone else can chime in? I am trying to get two windows to open full screen on two monitors.

**Comment by sh-dave** [comment]
Not sure if it still compiles, but a multiwindow example is actually already included in Kha/test/MultiWindow. Also multiwindow is only implemented for windows+opengl and linux builds. I don't know enough (and have no use for it at work) about d3d or macos to implement it there.
To open 2 windows in "fullscreen", use the kha.Display class to query the monitors and their dimensions, and open a borderless window for them.

**Comment by ImmanuelSamuel** [comment]
@sh-dave Thanks for the quick response. I searched the examples but couldnt find it. Missed the tests. Any idea on where I might find window management? Like opening and closing (hiding) windows?

**Pull request closed without merging**
